- name: Demonstrates building docker images from ansible playbook
  hosts: localhost
  tasks:
    - name: Build ubuntu ansible image
      docker_image:
          name: "tektutor/ansible-ubuntu"
          state: present
          dockerfile: Dockerfile
          path: .
